### ISSUE TITLE
allow @serializable besides @json

### ISSUE THREAD

**Issue by mariusa** [JairusSW/as-json#30]
Hi, would it be possible to please also allow `@serializable` besides / instead of `@json` ?

@serializable is more generic (similar to rust)
and would also make class declarations compatible with https://github.com/gagdiez/serial-as/tree/main/json

Thanks!

**Comment by JairusSW** [comment]
This would be possible, yes. I'll consider it

**Comment by mariusa** [comment]
Thanks for considering! Your call :)

**Comment by JairusSW** [comment]
Its possible to allow both. I don't want to remove `@json` because that would bring breaking changes which is bad practice in general

**Comment by mariusa** [comment]
Hi,

Asking here instead of opening another issue:
vscode shows a warning on `@json` line: 
`Cannot find name 'json'. Did you mean 'JSON' ?`

I have a tsconfig.json with
```
{
  "extends": "assemblyscript/std/assembly.json",
  "include": [
    "./**/*.ts"
  ]
}
```

Could something be added to `json-as/index.ts` to solve this?

**Comment by JairusSW** [comment]
I can do that for sure

**Comment by JairusSW** [comment]
@mariusa, I added support for this optionally. Both @json and @serializable work :)

**Comment by mariusa** [comment]
Thanks :)

**Comment by unicornware** [comment]
typescript wise, using `@JSON` didn't work for me, nor did `@json`.

i ended up creating global dts file

```ts
declare global {
  var json: ClassDecorator
}

export {}
```

and adding the dts file path to the `files` array in my tsconfig

```json
{
  "compilerOptions": {
    "allowImportingTsExtensions": false,
    "allowJs": false,
    "alwaysStrict": true,
    "composite": true,
    "declaration": true,
    "downlevelIteration": true,
    "noEmit": false,
    "noEmitOnError": true,
    "lib": ["esnext", "esnext.string"],
    "outDir": ".",
    "preserveConstEnums": false,
    "strictBindCallApply": false,
    "typeRoots": ["./node_modules/assemblyscript/std/types"],
    "types": ["assembly"],
    "verbatimModuleSyntax": false
  },
  "extends": "./tsconfig.json",
  "files": ["./typings/json-as/global.d.ts"],
  "include": ["**/assembly/**/*.ts"]
}
```
