### PR TITLE
fix: use NodeKind symbolic constants to support assemblyscript >=0.28.16

### LINKED ISSUE #188: Incompatible with assemblyscript@0.28.16: JSON.parse<SalesItemConfig>(dataJSON) throws
### Summary
json-as appears to be incompatible with assemblyscript@0.28.16 in our project.

When compiling WASM with assemblyscript@0.28.16, the following line fails at runtime during response parsing:

```ts
const salesItemConfig = JSON.parse<SalesItemConfig>(dataJSON);
```

### Environment
- json-as: ^1.3.4
- assemblyscript: 0.28.16 (problematic)
- assemblyscript: 0.28.15 (works)
- target: WASM (browser runtime)

### Behavior
- With assemblyscript@0.28.15: works normally.
- With assemblyscript@0.28.16: JSON.parse<SalesItemConfig>(dataJSON) throws at runtime.

### Request
Could you please help confirm whether this is a known compatibility issue with assemblyscript@0.28.16, and if there is a recommended json-as version or fix?

If needed, I can provide a minimal repro snippet.

### PR DESCRIPTION
**Pull request by yoyo837**
## Problem

assemblyscript **0.28.16** inserted a new `TupleType = 3` entry in the `NodeKind` enum (see [assemblyscript/assemblyscript@0.28.16 changelog](https://github.com/AssemblyScript/assemblyscript/releases)), shifting all subsequent enum values by +1:

| Symbol | 0.28.15 | 0.28.16 |
|---|---|---|
| `FieldDeclaration` | 54 | **55** |
| `MethodDeclaration` | 58 | **59** |
| `ClassDeclaration` | 51 | **52** |
| *(all values ≥ 3 shifted +1)* | | |

TypeScript's `const enum` causes these values to be **baked as numeric literals** at compile time into the generated `transform/lib/*.js` files. When assemblyscript is upgraded, those numbers silently become wrong.

### Symptom

With assemblyscript ≥ 0.28.16, `@json`-decorated classes are silently skipped during transform — fields and methods are not recognized — so `__SERIALIZE`, `__DESERIALIZE_SLOW`, and `__INITIALIZE` are never injected. At runtime this produces:

```
Could not deserialize JSON to type 'MyClass'
```

See issue #188 for full details.

## Fix

Import `NodeKind` at **runtime** from `assemblyscript/dist/assemblyscript.js` and replace all hard-coded numeric literals with symbolic constants (`NodeKind.FieldDeclaration`, `NodeKind.MethodDeclaration`, etc.) in:

- `transform/lib/index.js` — 4 occurrences (members, serializers, deserializers filters)
- `transform/lib/visitor.js` — 62 switch-case labels in `_visit()`

The TypeScript source files (`transform/src/`) already use the correct symbolic constants; the issue is only in the compiled output.

## Testing

Verified with both assemblyscript `0.28.15` and `0.28.16`: `@json` classes now have their methods correctly injected in both versions.

Closes #188

### CODE REVIEW

**Comment by JairusSW** [comment]
@yoyo837 please update the TypeScript files in `transform/src` instead of `transform/lib`. The problem is that when rebuilding the transform, your changes get overwritten.

Also, please add yourself to the contributors list in `package.json`

After that, it should be good to merge

**Comment by yoyo837** [comment]
Thanks for the review! I've updated the PR:

- Instead of hand-editing the compiled files in `transform/lib/`, I updated the `assemblyscript` devDependency from `^0.28.14` → `^0.28.16` in `package.json` and rebuilt the project with `npm run build:transform`
- The rebuild automatically generates correct `transform/lib/` files with the updated enum values (since assemblyscript 0.28.16 added `TupleType=3` to `NodeKind`, shifting all subsequent values by +1)
- Added `yoyo837` to the contributors list in `package.json`
- Bumped version to `1.3.5`

The transform source files in `transform/src/` already use symbolic constants (`NodeKind.Source`, `NodeKind.NamedType`, etc.) — the issue was just that the **compiled** JS had the old numeric values baked in from the older AssemblyScript version.

**Comment by yoyo837** [comment]
One more question about versioning — since AssemblyScript's insertion of `TupleType=3` in the `NodeKind` enum effectively shifts the numeric values baked into the compiled transform output, this seems like it could be considered a breaking change from json-as's perspective (older transform builds won't work with >=0.28.16, and vice versa).

Should this warrant a **minor** bump to `1.4.0` rather than a patch? Happy to adjust to whatever you think makes sense — just wanted to raise it 🙂

**Comment by JairusSW** [comment]
If you want to leave the version as-is, I'll bump manually. And yes, it is a breaking change

**Comment by yoyo837** [comment]
Done — I've reverted the version bump back to `1.3.4`, so the only changes in `package.json` now are the `assemblyscript` dependency upgrade and the contributor addition.

Also noted that the CI test failures appear to be pre-existing — the same `TS2304: Cannot find name 'JSON_MODE'` errors are present on the `main` branch as well and aren't related to this PR.

**Comment by JairusSW** [comment]
@yoyo837, thanks for the work and staying on top of issues. I've pushed a small patch that resolves `NodeKind` at runtime instead of compile time so that we can effectively avoid the breaking change

**Comment by yoyo837** [comment]
> @yoyo837, thanks for the work and staying on top of issues. I've pushed a small patch that resolves `NodeKind` at runtime instead of compile time so that we can effectively avoid the breaking change

Nice catch. This is clearly a better solution.
